### ISSUE TITLE
Bug in jupyter notebook (Fault 2_1 - Introduction to Voltage Glitching) : cw version 5.3.0

### ISSUE THREAD

**Issue by sopmacF** [newaetech/chipwhisperer-jupyter#20]
Dear all,

the glitch code on notebook "Fault 2_1" (which starts with "from importlib import reload") unfortunately has a bug (see figure).

![image](https://user-images.githubusercontent.com/38037801/93709490-c29f8600-fb3e-11ea-89e0-d395f669eb5a.png)

However, the code on [1] (see "In [9]" and following figure) is correct.

![image](https://user-images.githubusercontent.com/38037801/93709577-8c163b00-fb3f-11ea-8557-7bbf8dc244b2.png)

[1] : https://chipwhisperer.readthedocs.io/en/latest/tutorials/courses_fault101_soln_fault%202_1%20-openadc-cwlitearm.html#tutorial-courses-fault101-soln-fault-2-1-openadc-cwlitearm

Cheers,
Fabio

**Comment by colinoflynn** [comment]
Hi Fabio,

Check out the "SOLN" notebook for the "just works" version. Many of the notebooks in the course directory like this requires the student to add some code for them to work. 

We still provide the final SOLN version if you just want to run it!
