### ISSUE TITLE
dropbox sync problem with emoji in filename

### ISSUE THREAD

**Issue by mcsmonk** [newaetech/chipwhisperer-jupyter#24]
Sorry, I have a simple question. :sweat_smile:
Is there a special reason to use emoji "courses/sca101/generators/Lab* - GENERATOR 🏭.ipynb" ?
I use dropbox to sync multiple devices conveniently. But, the filename with emoji makes a sync problem.
[https://help.dropbox.com/en-en/installs-integrations/sync-uploads/files-not-syncing](https://help.dropbox.com/en-en/installs-integrations/sync-uploads/files-not-syncing)

**Comment by colinoflynn** [comment]
oops - didn't notice that! The filename is mostly so it appears in the list with an obvious note... we can drop those in the next release.

**Comment by mcsmonk** [comment]
I'm sorry to bother you. I checked comit f7aa41fb1d547d1d08f5dbaf6e945478278b74a0. Thank you for response.

**Comment by colinoflynn** [comment]
Great, thanks @alex-dewar for closing this one out!
