### ISSUE TITLE
'NoneType' object has no attribute 'serialstm32f'

### ISSUE THREAD

**Issue by NEswariDevi** [newaetech/chipwhisperer-jupyter#28]
We are the recent purchaser of the Chipwhisperer Pro 1200 kit.
We are trying to run the file '1 - Connecting to Hardware', unfortunately we are facing 'NoneType' object has no attribute 'serialstm32f' when we attempt to run the following command:

cw.program_target(scope, cw.programmers.STM32FProgrammer,"../hardware/victims/firmware/simpleserial-aes/simpleserial-aes-CW308_STM32F3.hex" )

We have followed all the commands preceding the mentioned one, as same in the '1 - Connecting to Hardware file'

Any steps we missed or how should we proceed?

**Comment by alex-dewar** [comment]
Fixed at https://forum.newae.com/t/nonetype-object-has-no-attribute-serialstm32f/2740/5
