### ISSUE TITLE
FAULT 104, wrong SimpleSerial Version

### ISSUE THREAD

**Issue by Securitybits-io** [newaetech/chipwhisperer-jupyter#30]
Simple typo, but on the latest version of the tutorial for Fault 104, the SimpleSerial pre-compile is set to 2_0, which errors the compilation defaulting back to 1_0.
Setting the SS_VER='SS_VER_2_1' successfully built and compiled the FW.

**Comment by alex-dewar** [comment]
Thanks for the report on this, I've updated the notebook
