### ISSUE TITLE
Lab 2_1A: Volatile Long Ints

### ISSUE THREAD

**Issue by Armannnnnn** [newaetech/chipwhisperer-jupyter#39]
Hi,

I have been working through Lab 2_1A using the ChipWhisperer NANO board. I am attempting to insert the multiply instructions; however, doing so results in a syntax error when initializing volatile long int A since Python doesn't support these keywords. I am pasting the instructions into a Jupyter cell and inserting them in that fashion. Maybe I am missing something about how to insert instructions?

**Comment by jpcrypt** [comment]
This is not Python code; it is meant to be inserted in the `simpleserial-base.c` file (part of the target firmware) that is mentioned earlier in the notebook.
If you still have difficulties, head over to forum.newae.com, it will be easier to help you there.
